// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleRentalStore.Data;

#nullable disable

namespace VehicleRentalStore.Migrations
{
    [DbContext(typeof(VehicleRentalDbContext))]
    [Migration("20260516154536_AddEmployeePassword")]
    partial class AddEmployeePassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CustomerRental", b =>
                {
                    b.Property<int>("AdditionalDriversId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RentalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdditionalDriversId", "RentalId");

                    b.HasIndex("RentalId");

                    b.ToTable("CustomerRental");
                });

            modelBuilder.Entity("RentalRentalItem", b =>
                {
                    b.Property<int>("RentalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RentedItemsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RentalId", "RentedItemsId");

                    b.HasIndex("RentedItemsId");

                    b.ToTable("RentalRentalItem");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.ConditionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EstimatedRepairCost")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRepaired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationOnVehicle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RentalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RentalId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ConditionLogs");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.IncidentCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdminFee")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBilledToCustomer")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OffenseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RentalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RentalId");

                    b.ToTable("IncidentCharges");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.InsurancePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DailyCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Deductible")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InsurancePlans");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RentalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RentalId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("PersonType").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DropoffLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndFuelPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndOdometerKm")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FuelPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InsurancePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecurityDepositReleased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PickupLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SecurityDepositAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartFuelPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartOdometerKm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DropoffLocationId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("InsurancePlanId");

                    b.HasIndex("PickupLocationId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.RentalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RentalItems");

                    b.HasDiscriminator<string>("ItemType").HasValue("RentalItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Customer", b =>
                {
                    b.HasBaseType("VehicleRentalStore.Models.Person");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriversLicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("LicenseCategories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Employee", b =>
                {
                    b.HasBaseType("VehicleRentalStore.Models.Person");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Addon", b =>
                {
                    b.HasBaseType("VehicleRentalStore.Models.RentalItem");

                    b.Property<int>("BillingType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FlatFee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("RentalItems", t =>
                        {
                            t.Property("Description")
                                .HasColumnName("Addon_Description");
                        });

                    b.HasDiscriminator().HasValue("Addon");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Vehicle", b =>
                {
                    b.HasBaseType("VehicleRentalStore.Models.RentalItem");

                    b.Property<double>("BatteryCapacityKWh")
                        .HasColumnType("REAL");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentOdometerKm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentTires")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExtraKilometerRate")
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelTankCapacityLiters")
                        .HasColumnType("REAL");

                    b.Property<int>("FuelType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IncludedKilometersPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextInspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NextMaintenanceOdometerKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RefuelingPremiumPerUnit")
                        .HasColumnType("TEXT");

                    b.Property<int>("Transmission")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Vehicle");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Car", b =>
                {
                    b.HasBaseType("VehicleRentalStore.Models.Vehicle");

                    b.Property<int>("CargoCapacityLiters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Car");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Motorcycle", b =>
                {
                    b.HasBaseType("VehicleRentalStore.Models.Vehicle");

                    b.Property<int>("EngineCapacityCc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresSpecialLicense")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Motorcycle");
                });

            modelBuilder.Entity("CustomerRental", b =>
                {
                    b.HasOne("VehicleRentalStore.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("AdditionalDriversId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleRentalStore.Models.Rental", null)
                        .WithMany()
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentalRentalItem", b =>
                {
                    b.HasOne("VehicleRentalStore.Models.Rental", null)
                        .WithMany()
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleRentalStore.Models.RentalItem", null)
                        .WithMany()
                        .HasForeignKey("RentedItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleRentalStore.Models.ConditionLog", b =>
                {
                    b.HasOne("VehicleRentalStore.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleRentalStore.Models.Rental", "Rental")
                        .WithMany("InspectionLogs")
                        .HasForeignKey("RentalId");

                    b.HasOne("VehicleRentalStore.Models.Vehicle", "Vehicle")
                        .WithMany("DamageHistory")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Rental");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.IncidentCharge", b =>
                {
                    b.HasOne("VehicleRentalStore.Models.Customer", null)
                        .WithMany("TrafficViolations")
                        .HasForeignKey("CustomerId");

                    b.HasOne("VehicleRentalStore.Models.Rental", "Rental")
                        .WithMany("IncidentCharges")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Invoice", b =>
                {
                    b.HasOne("VehicleRentalStore.Models.Rental", "Rental")
                        .WithMany()
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.MaintenanceLog", b =>
                {
                    b.HasOne("VehicleRentalStore.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleRentalStore.Models.Vehicle", "Vehicle")
                        .WithMany("MaintenanceHistory")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Rental", b =>
                {
                    b.HasOne("VehicleRentalStore.Models.Customer", "Customer")
                        .WithMany("Rentals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleRentalStore.Models.Location", "DropoffLocation")
                        .WithMany("Dropoffs")
                        .HasForeignKey("DropoffLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleRentalStore.Models.Employee", "Employee")
                        .WithMany("Rentals")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleRentalStore.Models.InsurancePlan", "InsurancePlan")
                        .WithMany("Rentals")
                        .HasForeignKey("InsurancePlanId");

                    b.HasOne("VehicleRentalStore.Models.Location", "PickupLocation")
                        .WithMany("Pickups")
                        .HasForeignKey("PickupLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DropoffLocation");

                    b.Navigation("Employee");

                    b.Navigation("InsurancePlan");

                    b.Navigation("PickupLocation");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.InsurancePlan", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Location", b =>
                {
                    b.Navigation("Dropoffs");

                    b.Navigation("Pickups");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Rental", b =>
                {
                    b.Navigation("IncidentCharges");

                    b.Navigation("InspectionLogs");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Customer", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("TrafficViolations");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Employee", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("VehicleRentalStore.Models.Vehicle", b =>
                {
                    b.Navigation("DamageHistory");

                    b.Navigation("MaintenanceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
